### ISSUE TITLE
Introduce a package for handling data retrieved from Astarte

### ISSUE THREAD

**Issue by Annopaolo** [astarte-platform/astarte-go#34]
Currently, data parsing is intertwined with HTTP-related functions in the `client` package. As stated in #30, we should move it away and rationalize code.

This partially relates to #33.

**Comment by matt-mazzucato** [comment]
After an IRL discussion, the `data` package shouldn't be factored out from the current codebase.
From a user point of view, factoring out the `data` package is not that meaningful as it provides capabilities for parsing data obtained by the Astarte client. We cannot think of use cases in which an external application would employ the `data` package when not dealing with the Astarte client.
In addition, from an implementation point of view, developing a `data` package would lead to the need of propagating states belonging to different entities, thus forcing to sync states between different packages.
Thus, include the logic (ideally) belonging to the `data` package within the `client` package.
